name: posts
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  dio: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: Noto Serif
      fonts:
        - asset: assets/fonts/noto-serif/NotoSerif-Thin.ttf
          weight: 100
        - asset: assets/fonts/noto-serif/NotoSerif-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto-serif/NotoSerif-Light.ttf
          weight: 300
        - asset: assets/fonts/noto-serif/NotoSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto-serif/NotoSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto-serif/NotoSerif-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto-serif/NotoSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto-serif/NotoSerif-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto-serif/NotoSerif-Black.ttf
          weight: 900
  uses-material-design: true
